name: Deploy Laravel Breeze to Hosting

on:
  push:
    branches:
      - main # Ubah ke 'master' jika default branch kamu adalah master

jobs:
  web-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install Composer Dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Install NPM & Build Vite
      run: |
        npm install
        npm run build

    - name: Sync files to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /htdocs/ # Folder public/utama di InfinityFree
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/vendor/**
          **/tests/**
          README.md
          .env.example